const q = (id, text, options, correctIndex) => ({
  id: `sim-cliente-${id}`,
  text,
  options,
  correct: options[correctIndex]
});

export const mockExamQuestionsCliente = [
  q(1, "¿Qué ventaja principal ofrecen los microservicios?", ["Aumentan el acoplamiento entre componentes", "Permiten desplegar partes de la aplicación de forma independiente", "Eliminan la necesidad de servidores", "Solo funcionan en aplicaciones pequeñas"], 1),
  q(2, "¿Qué lenguaje se utiliza para estructurar el contenido de una página web?", ["CSS", "JavaScript", "HTML", "Python"], 2),
  q(3, "¿Qué problema es común en el desarrollo web del lado cliente?", ["Acceso total al hardware", "Diferencias entre navegadores", "Eliminación del DOM", "Falta de conexión a internet"], 1),
  q(4, "¿Qué palabra clave permite declarar variables con alcance de bloque en JavaScript moderno?", ["var", "const", "static", "global"], 1),
  q(5, "¿Qué valor tiene una variable no definida en JavaScript?", ["null", "0", "undefined", "false"], 2),
  q(6, "¿Qué tipo de dato representa texto en JavaScript?", ["Number", "Boolean", "String", "Object"], 2),
  q(7, "¿Qué describe mejor un objeto en JavaScript?", ["Una función matemática", "Una estructura de datos con propiedades y valores", "Un tipo de bucle", "Una variable booleana"], 1),
  q(8, "¿Cuál de los siguientes es un objeto global en JavaScript?", ["document", "console", "Array", "Todas las anteriores"], 3),
  q(9, "¿Para qué sirve el objeto Date en JavaScript?", ["Manipular estilos CSS", "Gestionar fechas y horas", "Crear eventos", "Acceder al DOM"], 1),
  q(10, "¿Qué hace una función en JavaScript?", ["Almacena datos", "Ejecuta código reutilizable", "Define estilos", "Controla el navegador"], 1),
  q(11, "¿Cómo se declara una función flecha (arrow function)?", ["function() {}", "=> {}", "() => {}", "func => {}"], 2),
  q(12, "¿Qué es un array en JavaScript?", ["Un objeto HTML", "Una lista ordenada de elementos", "Un tipo de evento", "Una función especial"], 1),
  q(13, "¿Qué ocurre cuando un usuario hace clic en un botón?", ["Se ejecuta automáticamente CSS", "Se genera un evento", "Se recarga el servidor", "Se crea una variable"], 1),
  q(14, "¿Qué método permite eliminar un elemento del DOM?", ["deleteElement()", "remove()", "destroy()", "erase()"], 1),
  q(15, "¿Qué método se usa para seleccionar un elemento por ID?", ["querySelectorAll()", "getElementById()", "getElementsByClass()", "selectById()"], 1),
  q(16, "¿Qué ocurrirá al ejecutar este código?\n\nlet x = 10;\n\nif (true) {\n   let x = 20;\n}\n\nconsole.log(x);", ["20", "10", "undefined", "Error"], 1),
  q(17, "¿Qué devuelve este código?\n\nconsole.log(typeof null);", ["\"null\"", "\"object\"", "\"undefined\"", "Error"], 1),
  q(18, "¿Cuál es el resultado?\n\nconst arr = [1, 2, 3];\narr.push(4);\n\nconsole.log(arr);", ["Error", "[1, 2, 3]", "[1, 2, 3, 4]", "undefined"], 2),
  q(19, "¿Qué hace este código?\n\nconst btn = document.querySelector(\"button\");\n\nbtn.addEventListener(\"click\", () => alert(\"Hola\"));", ["Crea un botón", "Elimina un botón", "Añade un evento al hacer clic", "Recarga la página"], 2),
  q(20, "¿Cuál es el resultado?\n\nconsole.log(2 == \"2\");", ["false", "true", "Error", "undefined"], 1),
  q(21, "¿Qué método permite realizar peticiones HTTP de forma moderna en JavaScript?", ["ajax()", "fetch()", "httpRequest()", "request()"], 1),
  q(22, "¿Dónde se ejecuta JavaScript en una aplicación web?", ["En el servidor únicamente", "En la base de datos", "En el sistema operativo directamente", "En el navegador del cliente"], 3),
  q(23, "¿Qué almacenamiento se elimina al cerrar la pestaña?", ["localStorage", "cookies persistentes", "IndexedDB", "sessionStorage"], 3),
  q(24, "¿Qué tecnología permite almacenar grandes volúmenes de datos en el navegador?", ["Cookies", "sessionStorage", "IndexedDB", "HTML"], 2),
  q(25, "¿Qué significa API?", ["Application Programming Interface", "Advanced Programming Interface", "Automated Process Integration", "Application Process Internet"], 0),
  q(26, "¿Qué lenguaje define el diseño visual de una web?", ["HTML", "CSS", "JavaScript", "XML"], 1),
  q(27, "¿Qué propiedad inserta texto sin interpretar HTML?", ["innerHTML", "valueHTML", "textContent", "innerTextHTML"], 2),
  q(28, "¿Qué evento ocurre al enviar un formulario?", ["submit", "click", "change", "load"], 0),
  q(29, "¿Qué permite la API de geolocalización?", ["Guardar datos en el navegador", "Obtener la ubicación del dispositivo", "Crear bases de datos", "Ejecutar scripts"], 1),
  q(30, "¿Qué método se usa para obtener la ubicación actual?", ["getLocation()", "findPosition()", "getCurrentPosition()", "locateUser()"], 2),
  q(31, "¿Qué tecnología permite comunicación en tiempo real?", ["AJAX", "JSON", "HTTP", "WebSockets"], 3),
  q(32, "¿Qué hace el atributo \"required\" en un input?", ["Aplica estilos", "Hace el campo obligatorio", "Oculta el campo", "Envía el formulario automáticamente"], 1),
  q(33, "¿Qué evento se produce al cargar completamente la página?", ["click", "submit", "load", "change"], 2),
  q(34, "¿Qué método convierte un string a número entero?", ["parseInt()", "toString()", "NumberToInt()", "convert()"], 0),
  q(35, "¿Qué hace addEventListener()?", ["Elimina eventos", "Ejecuta funciones automáticamente", "Añade un manejador de eventos", "Recarga la página"], 2),
  q(36, "¿Qué devuelve querySelector()?", ["Todos los elementos", "Un array", "El primer elemento que coincide", "Un objeto JSON"], 2),
  q(37, "¿Qué propiedad permite acceder al valor de un input?", ["innerHTML", "textContent", "value", "inputText"], 2),
  q(38, "¿Qué lenguaje se usa normalmente en APIs modernas?", ["HTML", "CSS", "JSON", "SQL"], 2),
  q(39, "¿Qué etiqueta HTML se utiliza para incluir JavaScript?", ["<js>", "<script>", "<javascript>", "<code>"], 1),
  q(40, "¿Qué ocurre si accedes a una propiedad que no existe en un objeto?", ["Error", "null", "undefined", "false"], 2),
  q(41, "¿Qué método se usa para añadir un elemento al final de un array?", ["push()", "add()", "append()", "insert()"], 0),
  q(42, "¿Qué hace preventDefault() en un evento?", ["Elimina el elemento", "Detiene la propagación", "Evita el comportamiento por defecto", "Crea un evento nuevo"], 2),
  q(43, "¿Qué hace setTimeout()?", ["Ejecuta código inmediatamente", "Ejecuta código después de un tiempo", "Repite código continuamente", "Detiene una función"], 1),
  q(44, "¿Qué método permite convertir un string a número decimal?", ["parseInt()", "Number()", "parseFloat()", "toNumber()"], 2),
  q(45, "¿Qué hace classList.add()?", ["Elimina clases", "Añade una clase CSS", "Cambia el HTML", "Oculta el elemento"], 1),
  q(46, "Una startup quiere desarrollar una aplicación web sencilla con posibilidad de crecer en el futuro. El equipo es pequeño y no tiene mucha experiencia en sistemas distribuidos. ¿Qué arquitectura es más recomendable?", ["Microservicios complejos", "Monolítica modular", "Serverless puro", "Arquitectura basada en mainframe"], 1),
  q(47, "Selección de Tecnología Frontend. El equipo decide usar una tecnología que ayude a detectar errores durante el desarrollo mediante tipado. ¿Qué opción es la más adecuada?", ["JavaScript puro", "HTML5", "TypeScript", "CSS"], 2),
  q(48, "Comunicación en Tiempo Real. Una aplicación requiere chat entre usuarios y notificaciones instantáneas sin recargar la página. ¿Qué tecnología es la más adecuada?", ["AJAX", "Fetch API", "WebSockets", "LocalStorage"], 2),
  q(49, "Gestión de Variables. En un simulador necesitas definir una constante que no cambie durante la ejecución. ¿Qué palabra clave usarías?", ["var", "let", "static", "const"], 3),
  q(50, "Estructuras de Control. En una estructura if / else if / else, ¿qué ocurre cuando una condición es verdadera?", ["Se ejecutan todos los bloques", "Solo se ejecuta el último bloque", "Se ejecuta el primer bloque verdadero", "No se ejecuta ninguno"], 2),
  q(51, "Operaciones en JavaScript. Si tienes stock = 15 y ejecutas stock -= 5, ¿cuál es el resultado?", ["20", "10", "-5", "15"], 1),
  q(52, "Problemas de Integración. Un botón no responde al hacer clic. El script está correctamente enlazado, pero el código JavaScript se ejecuta antes de que el DOM esté cargado. ¿Cuál es la causa?", ["Error en CSS", "Problema de red", "El script se ejecuta antes de cargar el DOM", "Falta un servidor"], 2),
  q(53, "Selección de Elementos. Quieres seleccionar un elemento por su id en JavaScript. ¿Qué método es correcto?", ["querySelectorAll()", "getElementById()", "getElementsByClassName()", "findElement()"], 1),
  q(54, "Manejo de Eventos. ¿Qué método se usa para asociar una función a un evento?", ["addEventListener()", "createEvent()", "attachFunction()", "onClickAdd()"], 0),
  q(55, "Depuración de Código. Un script no se ejecuta y en consola aparece “404 script.js”. ¿Qué significa?", ["Error de sintaxis", "Archivo no encontrado", "Problema de CSS", "Solo funcionan en aplicaciones pequeñas"], 1),
  q(56, "Gestor de Proyectos. En una aplicación de gestión de tareas, se quiere que al pulsar un botón “Abrir Proyecto” se abra una nueva pestaña con los detalles del proyecto seleccionado. ¿Qué método es el más adecuado?", ["document.createElement()", "addEventListener()", "window.open()", "console.log()"], 2),
  q(57, "Gestión de Inventario. Observa el código:\n\nlet inventario = [];\ninventario.push({ nombre: \"Zapatos\", precio: 50 });\n\n¿Qué efecto tiene push() en este caso?", ["Elimina el último producto", "Añade un producto al inventario", "Ordena el inventario", "Busca un producto"], 1),
  q(58, "Dado el siguiente código, ¿por qué se usa toLowerCase()?\n\nconst nombre = \"CAMISETA\";\nconst resultado = nombre.toLowerCase();", ["Para eliminar espacios", "Para convertir números", "Para comparar sin importar mayúsculas", "Para dividir texto"], 2),
  q(59, "¿Qué devuelve este método?\n\ngetInfo() {\n   return `Producto: ${this.nombre}`;\n}", ["Un número", "Un array", "Un objeto", "Un texto con información del producto"], 3),
  q(60, "Validación de Stock. ¿Qué muestra por consola este código?\n\nlet stock = -3;\n\nif (stock < 0) {\n   stock = 0;\n} else if (stock === 0) {\n   stock += 5;\n}\n\nconsole.log(stock);", ["-3", "0", "5", "Error"], 1),
  q(61, "Formularios Accesibles. ¿Qué función tiene el atributo for?", ["Validar el campo", "Enviar datos", "Aplicar estilos", "Asociar label con input"], 3),
  q(62, "Problema de Eventos. Un botón no responde al hacer clic. El JavaScript se ejecuta antes de que el HTML esté completamente cargado. ¿Cuál es la causa más probable?", ["Error en CSS", "Script ejecutado antes del DOM", "Problema de servidor", "Error en variables"], 1),
  q(63, "Arrays. ¿Qué ocurre en esta línea de código?\n\nconst productos = [\"A\", \"B\"];\nproductos.pop();", ["Se añade un elemento", "Se elimina el primero", "Se elimina el último", "Se ordena"], 2),
  q(64, "Validación de Formularios. Un formulario se envía automáticamente al hacer clic en un botón, pero el desarrollador quiere evitarlo. ¿Qué método debe usar?", ["stopPropagation()", "preventDefault()", "cancelEvent()", "stopSubmit()"], 1),
  q(65, "Validación de Formularios. Un desarrollador quiere validar un formulario antes de enviarlo y decide usar JavaScript para evitar el envío automático si hay errores. ¿Qué efecto tiene este código?\n\nform.addEventListener(\"submit\", function(e) {\n   e.preventDefault();\n});", ["Envía el formulario automáticamente", "Evita el envío del formulario", "Elimina el formulario del DOM", "Recarga la página"], 1),
  q(66, "Validación de Email. En un formulario se usa el siguiente código. ¿Qué validación realiza automáticamente el navegador?\n\n<input type=\"email\" required></input>", ["Comprueba que el campo no esté vacío y tenga formato email", "Guarda el correo en el servidor", "Valida con una API externa", "Aplica estilos automáticamente"], 0),
  q(67, "Accesibilidad. Un desarrollador añade el atributo aria-live=\"polite\" en un mensaje de error. ¿Qué significa esto?", ["El mensaje no se mostrará", "Se mostrará solo visualmente", "Los lectores de pantalla anunciarán cambios sin interrumpir", "Valida automáticamente el formulario"], 2),
  q(68, "Manipulación del DOM. En una lista de tareas, se quiere marcar una tarea como completada al hacer clic. ¿Qué hace este código?\n\nelement.classList.toggle(\"completada\");", ["Elimina el elemento", "Añade o quita la clase según exista", "Duplica el elemento", "Cambia el texto"], 1),
  q(69, "Interacción con Inputs. En una aplicación de tareas, tras añadir un elemento, se quiere limpiar el campo de texto. ¿Qué código es correcto?", ["input.delete()", "input.value = \"\"", "input.value == \"\"", "input.reset()"], 1),
  q(70, "Validación de Formularios. Un desarrollador quiere validar que un campo de contraseña tenga al menos 8 caracteres sin usar JavaScript. ¿Qué atributo HTML debería usar?", ["minlength=\"8\"", "required", "pattern=\"[0-9]\"", "max=\"8\""], 0),
  q(71, "Eventos de Formularios. ¿Qué ocurre cuando el usuario envía el formulario?\n\nform.addEventListener(\"submit\", validar);", ["Se recarga automáticamente", "Se ejecuta la función validar", "Se elimina el formulario", "Se bloquea el navegador"], 1),
  q(72, "Validación de Inputs. Un desarrollador utiliza el siguiente input en un formulario:\n\n<input type=\"number\" min=\"1\" max=\"10\" value=\"15\"></input>\n\nEl usuario intenta enviar el formulario sin modificar el valor. ¿Qué ocurrirá?", ["El formulario se envía con valor 15", "El navegador corrige automáticamente el valor a 10", "El formulario no se envía porque el valor es inválido", "Se convierte el valor en texto"], 2),
  q(73, "DOM. ¿Qué devuelve?\n\ndocument.querySelector(\"#btn\");", ["Todos los botones", "Un array", "El primer elemento que coincide", "Un evento"], 2),
  q(74, "Eventos. ¿Qué ocurre al hacer clic?\n\nbtn.addEventListener(\"click\", () => alert(\"OK\"));", ["Se elimina el botón", "Se muestra un mensaje", "Se recarga la página", "No ocurre nada"], 1),
  q(75, "Manipulación DOM. ¿Qué ocurre?\n\nelement.innerHTML = \"<b>Hola</b>\";", ["Se añade texto plano", "Se interpreta HTML", "Se elimina el elemento", "Error"], 1),
  q(76, "Estructura HTML. En un documento HTML, ¿qué elemento debe contener el contenido principal único?", ["<header>", "<main>", "<section>", "<div>"], 1),
  q(77, "Accesibilidad. Un <label> está correctamente asociado a un <input>. ¿Qué mejora esto?", ["Velocidad", "Accesibilidad", "Seguridad", "Almacenamiento"], 1),
  q(78, "Carga de Scripts.\n\n<script src=\"app.js\"></script>\n\n¿Qué ocurre si la ruta es incorrecta?", ["Se ignora automáticamente", "Se ejecuta vacío", "Se carga parcialmente", "Error en consola"], 3),
  q(79, "Almacenamiento. ¿Qué almacenamiento persiste tras cerrar el navegador?", ["sessionStorage", "localStorage", "variables JS", "cookies de sesión"], 1),
  q(80, "Sesión. ¿Qué ocurre con sessionStorage?", ["Es permanente", "Se guarda en servidor", "Se borra al cerrar pestaña", "No se puede usar"], 2),
  q(81, "Offline. Una app necesita funcionar sin Internet. ¿Qué usarías?", ["AJAX", "Cookies", "Service Worker", "HTML"], 2),
  q(82, "Geolocalización.\n\nnavigator.geolocation.getCurrentPosition(...)\n\n¿Qué hace?", ["Guarda datos", "Obtiene ubicación", "Crea mapa", "Envía datos"], 1),
  q(83, "Permisos. El usuario rechaza la geolocalización. ¿Qué debes hacer?", ["Bloquear la app", "Forzar acceso", "Dar alternativa", "Ignorar error"], 2),
  q(84, "Datos Complejos. Necesitas guardar datos estructurados y hacer búsquedas. ¿Qué usar?", ["localStorage", "sessionStorage", "IndexedDB", "variables"], 2),
  q(85, "Dashboard de Noticias Dinámico. En un dashboard se cargan noticias desde una API y se insertan dentro de:\n\n<section id=\"noticias-container\" class=\"grid\"></section>\n\n¿Qué función cumple este elemento?", ["Guardar las noticias en localStorage", "Mostrar dinámicamente las noticias en la página", "Ejecutar automáticamente la API", "Validar los datos recibidos"], 1),
  q(86, "Indicador de Carga. Observa el elemento:\n\n<p id=\"loading-indicator\" hidden>Cargando noticias...</p>\n\n¿Qué efecto tiene inicialmente el atributo hidden?", ["Elimina el elemento del HTML", "Oculta visualmente el elemento", "Cambia su color", "Impide seleccionarlo con JavaScript"], 1),
  q(87, "Mensajes de Error. En una aplicación que carga noticias, se incluye:\n\n<p id=\"error-message\" class=\"error\" hidden></p>\n\n¿Para qué se usaría principalmente?", ["Para mostrar errores de carga o conexión", "Para guardar noticias favoritas", "Para cambiar la categoría seleccionada", "Para crear nuevas noticias"], 0),
  q(88, "Filtro por Categoría. Un usuario selecciona “Deportes” en un <select>. La aplicación debe mostrar solo noticias de esa categoría. ¿Qué debería hacer JavaScript?", ["Cambiar el idioma del navegador", "Borrar el archivo HTML", "Filtrar las noticias según el valor seleccionado", "Desactivar todos los estilos CSS"], 2),
  q(89, "Persistencia de Tareas. Una aplicación de tareas debe recordar la lista aunque el usuario cierre el navegador y vuelva al día siguiente. ¿Qué tecnología es más adecuada?", ["sessionStorage", "variables globales", "localStorage", "alert()"], 2),
  q(90, "Datos Temporales. Un filtro solo debe conservarse mientras la pestaña actual esté abierta. Al cerrarla, debe perderse. ¿Qué opción usarías?", ["sessionStorage", "localStorage", "IndexedDB", "cookies persistentes"], 0)
];
