const q = (id, text, options, correctIndex) => ({
  id: `sim-ingles-profesional-${id}`,
  text,
  options,
  correct: options[correctIndex]
});

export const mockExamQuestionsInglesProfesional = [
  q(1, "If she caught the plane, she ... arrive in time.", ["would", "will", "does", "did"], 0),
  q(2, "If I could, I ... go shopping with you, darling.", ["went", "would", "must", "will"], 1),
  q(3, "Girls, you ... say those things about your teachers.", ["mustn’t", "haven’t to", "haven’t", "mustn’t to"], 0),
  q(4, "I ... write to Jennifer. I haven’t written to her for ages.", ["must to", "have that", "have", "must"], 3),
  q(5, "Your problem is not difficult. It’s ... than ours.", ["easier", "easiest", "more easy", "most easy"], 0),
  q(6, "My mother’s dress is ... than my aunt’s.", ["more long", "longest", "longer", "the longest"], 2),
  q(7, "By lunch time she will ... all the letters.", ["have typed", "had typed", "have type", "had type"], 0),
  q(8, "By twelve o’clock they will ... running for two hours.", ["be", "have been", "have", "been"], 1),
  q(9, "My secretary was late. She had never ... late before.", ["was", "had", "been", "came"], 2),
  q(10, "When the two boys arrived, most of their friends ...", ["have left", "had left", "have leave", "had leave"], 1),
  q(11, "What door is that? I think it is the ...", ["main door", "door the main", "main’s door", "door’s main"], 0),
  q(12, "Sandra is ... came to the party wearing that funny dress.", ["one which", "that who", "what", "the one who"], 3),
  q(13, "Darling, ... did you have dinner with, last night?", ["who", "that", "which", "whose"], 0),
  q(14, "The man ... I met yesterday, had an accident on the way here.", ["whose", "whom", "to who", "which"], 1),
  q(15, "The Bristol train ... It was half an hour late.", ["has just arrived", "has arrived just", "arrived has just", "just has arrived"], 0),
  q(16, "Have another piece of cake. No, thanks, ... too much.", ["I’ve ate", "I ate", "I eaten", "I’ve eaten"], 3),
  q(17, "I think my brother ... to come next month.", ["can", "could", "will be", "will be able"], 3),
  q(18, "Sorry, monsieur, I don’t speak French. ... you speak English?", ["Can’t", "Will", "Are able", "Would"], 3),
  q(19, "Mr. Brown ... for a loan, but then, he won the lottery.", ["has asked", "asks", "was asking", "was going to ask"], 3),
  q(20, "Little Susan ... TV when we got there.", ["watch", "watched", "was watching", "saw"], 2),
  q(21, "Jimmy, ... champagne on Christmas day?", ["you drink", "are you going to drink", "are you to drink", "drink you"], 1),
  q(22, "Every day he ... four or five miles. He is very fit.", ["is running", "runs", "run", "is going to run"], 1),
  q(23, "That child is ... big! He’s like his father.", ["so many", "so", "so much", "as"], 1),
  q(24, "What did you ... ? I couldn’t hear you.", ["say", "tell", "said", "told"], 0),
  q(25, "Will you come to the party tonight? I am ...", ["afraid", "afraid not", "don’t afraid", "fear not"], 1),
  q(26, "When did you finish ... your book?", ["to write", "to writing", "write", "writing"], 3),
  q(27, "You must have something to eat before ... to school.", ["go", "going", "to go", "of go"], 1),
  q(28, "Did you ... in the London marathon last year?", ["run", "ran", "runed", "running"], 0),
  q(29, "At what time did you ... to the bingo last night?", ["went", "go", "going", "to go"], 1),
  q(30, "The children haven’t ... from school yet.", ["come", "came", "coming", "comed"], 0),
  q(31, "That yellow bicycle on the corner is ...", ["the John’s bicycle", "John’s the bicycle", "the John’s the bicycle", "John’s bicycle"], 3),
  q(32, "The little boy is playing with ... toys.", ["her", "its", "their", "his"], 3),
  q(33, "Is there ... tea in the cup? No, there isn’t much.", ["much", "many", "a lot", "some"], 0),
  q(34, "How much money ... you spend on Saturdays?", ["does", "do", "don’t", "doesn’t"], 1),
  q(35, "Jeff, ... you go to that pub every day?", ["do", "does", "doesn’t", "don’t"], 0),
  q(36, "My mother usually ... fresh bread every morning.", ["is buying", "buy", "buys", "bought"], 2),
  q(37, "My daughter ... to England every year.", ["go", "is going", "went", "goes"], 3),
  q(38, "There ... only a little coffee in the cup.", ["was", "were", "had", "have"], 0),
  q(39, "There ... several boys playing in the middle of the road.", ["was", "were", "had", "have"], 1),
  q(40, "We haven’t been to Scotland ... 1988.", ["for", "during", "since", "until"], 2),
  q(41, "Haven’t you done your homework ...?", ["still", "already", "since", "yet"], 3),
  q(42, "How old are you? I ...", ["am 20 years old", "am 20 years", "have 20 years", "have 20 years old"], 0),
  q(43, "That is old Mrs Cohn. How ... she?", ["many years has", "old has", "many years is", "old is"], 3),
  q(44, "Sheila, ... go to the disco tonight.", ["let we", "let us", "we let", "we let’s"], 1),
  q(45, "My father wants to see Nora. ... come here at once.", ["tell she", "tell her", "let she", "let her"], 1),
  q(46, "This man is ... Mr Wilson, perhaps taller.", ["as tall as", "so tall so", "as tall so", "so tall as"], 0),
  q(47, "She has been ill, but she certainly ... today.", ["look best", "looks better", "looks best", "is best"], 1),
  q(48, "Jennifer ... out to the cinema by your brother.", ["has taken", "was taken", "is taken", "is going"], 1),
  q(49, "My brother wrote this article. It ... by my brother.", ["will be wrote", "was write", "was written", "is written"], 2),
  q(50, "Mary, ... you go out if you felt better?", ["will", "shall", "would", "should"], 2),
  q(51, "Boys, ... here, will you?", ["you come", "come", "comes", "to come"], 1),
  q(52, "Hello, darling, have you ... dinner yet?", ["make", "do", "made", "done"], 2),
  q(53, "I’m going to the kitchen to ... some coffee.", ["make", "do", "made", "did"], 0),
  q(54, "“How are you going to travel?” “... car, of course.”", ["On", "In", "By", "In the"], 2),
  q(55, "How ... you go to the hypermarket tomorrow?", ["did", "will", "shall", "—"], 1),
  q(56, "“Where did you park the car?” “It’s ... Pyrland Road.”", ["on", "into", "at", "in"], 0),
  q(57, "Tommy, don’t sit on the floor, sit ... the chair.", ["on", "at", "in", "by"], 2),
  q(58, "No, I ... to have anything to eat today.", ["am no going", "am not going", "don’t go", "go not"], 1),
  q(59, "What ... to drink today, wine or beer? Wine, please.", ["are you going", "are you", "are going", "do you"], 0),
  q(60, "That green car on the corner is my ...", ["father’s the car", "father’s car", "car’s father", "car’s the father"], 1)
];
